package: 'aviary'
name: 'CompositePipeline'
config:
  plugins_dir_path: 'my_plugin'

  pipeline_configs:
    - package: 'aviary'
      name: 'TilePipeline'
      config:
        show_progress: true

        grid_config:
          geojson_path: 'input/boundary.geojson'
          ignore_json_path: 'output/processed.json'
          strict_ignore_json_path: false
          tile_size: 100
          epsg_code: 25832
          num_chunks: 500
          chunk: 93

        tile_fetcher_config:
          package: 'aviary'
          name: 'WMSFetcher'
          config:
            url: 'https://www.wms.nrw.de/geobasis/wms_nw_dop'
            version: '1.3.0'
            layer: 'nw_dop_rgb'
            epsg_code: 25832
            response_format: 'image/png'
            channel_names:
              - 'r'
              - 'g'
              - 'b'
            tile_size: 100
            ground_sampling_distance: .2
            buffer_size: 20

        tile_loader_config:
          batch_size: 2
          max_num_threads: null
          num_prefetched_tiles: 0

        tiles_processor_config:
          package: 'aviary'
          name: 'SequentialCompositeProcessor'
          config:
            tiles_processor_configs:
              - package: 'my_plugin'
                name: 'VehicleModel'
                config:
                  r_channel_name: 'r'
                  g_channel_name: 'g'
                  b_channel_name: 'b'
                  vehicle_channel_name: 'vehicle'
              - package: 'aviary'
                name: 'RemoveBufferProcessor'
                config:
              - package: 'aviary'
                name: 'ObjectExporter'
                config:
                  channel_name: 'vehicle'
                  epsg_code: 25832
                  path: 'output/vehicle.gpkg'
                  mode: 'point'
              - package: 'aviary'
                name: 'GridExporter'
                config:
                  path: 'output/processed.json'

    - package: 'aviary'
      name: 'VectorPipeline'
      config:
        show_progress: true

        vector_loader_config:
          package: 'aviary'
          name: 'CompositeLoader'
          config:
            vector_loader_configs:
              - package: 'aviary'
                name: 'GPKGLoader'
                config:
                  path: 'output/vehicle.gpkg'
                  epsg_code: 25832
                  layer_name: 'vehicle'
              - package: 'aviary'
                name: 'GeoJSONLoader'
                config:
                  path: 'input/boundary.geojson'
                  epsg_code: 25832
                  layer_name: 'boundary'

        vector_processor_config:
          package: 'aviary'
          name: 'SequentialCompositeProcessor'
          config:
            vector_processor_configs:
              - package: 'aviary'
                name: 'ClipProcessor'
                config:
                  layer_name: 'vehicle'
                  mask_layer_name: 'boundary'
              - package: 'aviary'
                name: 'QueryProcessor'
                config:
                  layer_name: 'vehicle'
                  query_string: 'score > 0.5'
              - package: 'aviary'
                name: 'MapFieldProcessor'
                config:
                  layer_name: 'vehicle'
                  field: 'value'
                  mapping:
                    9: 'Large vehicle'
                    10: 'Small vehicle'
              - package: 'aviary'
                name: 'VectorExporter'
                config:
                  layer_name: 'vehicle'
                  epsg_code: 25832
                  path: 'output/vehicle.gpkg'
