package: 'aviary'
name: 'TilePipeline'
config:
  show_progress: true

  grid_config:
    bounding_box_coordinates:
      - 362000
      - 5714500
      - 364000
      - 5716500
    tile_size: 500

  tile_fetcher_config:
    package: 'aviary'
    name: 'CompositeFetcher'
    config:
      tile_fetcher_configs:
        - package: 'aviary'
          name: 'WMSFetcher'
          config:
            url: 'https://www.wms.nrw.de/geobasis/wms_nw_dop'
            version: '1.3.0'
            layer: 'nw_dop_rgb'
            epsg_code: 25832
            response_format: 'image/png'
            channel_names:
              - 'r'
              - null
              - null
            tile_size: 500
            ground_sampling_distance: .2
        - package: 'aviary'
          name: 'WMSFetcher'
          config:
            url: 'https://www.wms.nrw.de/geobasis/wms_nw_dop'
            version: '1.3.0'
            layer: 'nw_dop_nir'
            epsg_code: 25832
            response_format: 'image/png'
            channel_names:
              - 'nir'
              - null
              - null
            tile_size: 500
            ground_sampling_distance: .2

  tile_loader_config:
    batch_size: 4
    max_num_threads: null
    num_prefetched_tiles: 1

  tiles_processor_config:
    package: 'aviary'
    name: 'SequentialCompositeProcessor'
    config:
      tiles_processor_configs:
        - package: 'aviary'
          name: 'ExpressionProcessor'
          config:
            expression_string: '(nir - r) / (nir + r)'
            new_channel_name: 'ndvi'
            dtype: 'float32'
        - package: 'aviary'
          name: 'RasterExporter'
          config:
            channel_names: 'ndvi'
            epsg_code: 25832
            path: 'output/ndvi'
